# Generated by Django 5.2.1 on 2025-05-20 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP atual da máquina nesta configuração.', unique=True, verbose_name='Endereço IP')),
                ('hostname_rede', models.CharField(blank=True, help_text='Nome que a máquina está usando na rede (pode ser diferente do patrimônio)', max_length=100, null=True, verbose_name='Hostname na Rede')),
                ('ativo', models.BooleanField(default=True, help_text='Marque se esta é a configuração de rede atual para a máquina física.', verbose_name='Configuração Ativa?')),
                ('data_deteccao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Detecção/Cadastro')),
                ('ultima_verificacao', models.DateTimeField(auto_now=True, verbose_name='Última Verificação')),
                ('observacoes_config', models.TextField(blank=True, null=True, verbose_name='Observações da Configuração')),
            ],
            options={
                'verbose_name': 'Configuração de Rede',
                'verbose_name_plural': 'Configurações de Rede',
                'ordering': ['-ativo', '-data_deteccao'],
            },
        ),
        migrations.CreateModel(
            name='MaquinaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_patrimonio', models.CharField(help_text='Identificador único do equipamento físico. Ex: PAT00123, LAB01-PC05', max_length=100, unique=True, verbose_name='Nome/Patrimônio')),
                ('mac_address', models.CharField(blank=True, help_text='MAC Address da placa de rede principal. Ex: 00:1A:2B:3C:4D:5E', max_length=17, null=True, unique=True, verbose_name='Endereço MAC Principal')),
                ('tipo_equipamento', models.CharField(blank=True, help_text='Ex: Desktop, Notebook, Impressora, Servidor', max_length=50, null=True, verbose_name='Tipo de Equipamento')),
                ('setor', models.CharField(blank=True, help_text='Setor onde o equipamento está fisicamente localizado', max_length=50, null=True, verbose_name='Setor de Localização')),
                ('observacoes_hardware', models.TextField(blank=True, null=True, verbose_name='Observações do Hardware')),
                ('posicao_x', models.IntegerField(default=10, help_text='Coordenada X no layout visual (em pixels)', verbose_name='Posição X no Layout')),
                ('posicao_y', models.IntegerField(default=10, help_text='Coordenada Y no layout visual (em pixels)', verbose_name='Posição Y no Layout')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data da Última Atualização')),
                ('usuario_responsavel', models.ForeignKey(blank=True, help_text='Usuário principal ou responsável pelo equipamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Máquina Física',
                'verbose_name_plural': 'Máquinas Físicas',
                'ordering': ['nome_patrimonio'],
            },
        ),
        migrations.DeleteModel(
            name='Maquina',
        ),
        migrations.AddField(
            model_name='configuracaorede',
            name='maquina_fisica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_rede', to='maquinas.maquinafisica', verbose_name='Máquina Física Associada'),
        ),
    ]
