# Generated by Django 5.2.1 on 2025-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_configuracaorede_maquinafisica_delete_maquina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorede',
            name='codigo_simo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código SIMO'),
        ),
        migrations.AddField(
            model_name='configuracaorede',
            name='login_padrao_sistema_a',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Login Padrão (Sistema A)'),
        ),
        migrations.AddField(
            model_name='configuracaorede',
            name='ramal_telefonico',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ramal Telefônico'),
        ),
        migrations.AddField(
            model_name='configuracaorede',
            name='senha_padrao_sistema_a',
            field=models.CharField(blank=True, help_text='Considere implicações de segurança ao armazenar senhas.', max_length=128, null=True, verbose_name='Senha Padrão (Sistema A)'),
        ),
    ]
