# Generated by Django 5.2.1 on 2025-05-22 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_configuracaorede_codigo_simo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantaLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Joinville - Térreo, Poá - Escritório TI', max_length=100, unique=True, verbose_name='Nome da Planta/Layout')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem_fundo', models.ImageField(blank=True, help_text='Faça upload de uma imagem para o fundo do layout.', null=True, upload_to='plantas_baixas/', verbose_name='Imagem de Fundo (Planta Baixa)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data da Última Atualização')),
            ],
            options={
                'verbose_name': 'Planta do Layout',
                'verbose_name_plural': 'Plantas dos Layouts',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='maquinafisica',
            options={'ordering': ['planta_layout', 'nome_patrimonio'], 'verbose_name': 'Máquina Física', 'verbose_name_plural': 'Máquinas Físicas'},
        ),
        migrations.AlterField(
            model_name='configuracaorede',
            name='login_padrao_sistema_a',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Login Padrão (Servidor/Acesso Remoto)'),
        ),
        migrations.AlterField(
            model_name='configuracaorede',
            name='senha_padrao_sistema_a',
            field=models.CharField(blank=True, help_text='Considere implicações de segurança ao armazenar senhas.', max_length=128, null=True, verbose_name='Senha Padrão (Servidor/Acesso Remoto)'),
        ),
        migrations.AlterField(
            model_name='maquinafisica',
            name='setor',
            field=models.CharField(blank=True, help_text='Setor onde o equipamento está fisicamente localizado (dentro da planta)', max_length=50, null=True, verbose_name='Setor de Localização'),
        ),
        migrations.AddField(
            model_name='maquinafisica',
            name='planta_layout',
            field=models.ForeignKey(help_text='A qual planta ou layout esta máquina pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_fisicas', to='maquinas.plantalayout', verbose_name='Planta do Layout Associada'),
        ),
    ]
