# Generated by Django 5.2.1 on 2025-05-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0004_plantalayout_alter_maquinafisica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinafisica',
            options={'verbose_name': 'Máquina Física'},
        ),
        migrations.AlterField(
            model_name='maquinafisica',
            name='tipo_equipamento',
            field=models.CharField(choices=[('DESKTOP', 'Desktop'), ('NOTEBOOK', 'Notebook / Laptop'), ('IMPRESSORA', 'Impressora'), ('SERVIDOR', 'Servidor'), ('ROTEADOR', 'Roteador'), ('SWITCH', 'Switch de Rede'), ('TELEFONE_IP', 'Telefone IP'), ('OUTRO', 'Outro'), ('DESCONHECIDO', 'Desconhecido')], default='DESCONHECIDO', help_text='Selecione o tipo do equipamento.', max_length=20, verbose_name='Tipo de Equipamento'),
        ),
    ]
