# Generated by Django 5.2.1 on 2025-05-25 03:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0005_alter_maquinafisica_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Um breve resumo do problema. Ex: 'Computador não liga', 'Impressora atolando papel'", max_length=200, verbose_name='Título do Chamado/Problema')),
                ('descricao_problema', models.TextField(verbose_name='Descrição Detalhada do Problema')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO_PECA', 'Aguardando Peça'), ('AGUARDANDO_TERCEIRO', 'Aguardando Terceiro'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status do Chamado')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Abertura')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('solucao_aplicada', models.TextField(blank=True, null=True, verbose_name='Solução Aplicada')),
                ('maquina_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='maquinas.maquinafisica', verbose_name='Máquina com Problema')),
                ('responsavel_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Atendimento (TI)')),
                ('usuario_reportou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_reportados', to=settings.AUTH_USER_MODEL, verbose_name='Reportado Por')),
            ],
            options={
                'verbose_name': 'Chamado / Incidente',
                'verbose_name_plural': 'Chamados / Incidentes',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
