# Generated by Django 5.2.1 on 2025-05-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0006_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorede',
            name='data_ultima_verificacao_status',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Verificação de Status'),
        ),
        migrations.AddField(
            model_name='configuracaorede',
            name='ultimo_status_online',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Último Status Online'),
        ),
    ]
